name: drag_and_drop_flutter_platform_interface
description: A common platform interface for the drag_and_drop_flutter plugin.
version: 0.2.1
homepage: https://github.com/Jjagg/drag_and_drop_flutter/tree/main/packages/drag_and_drop_flutter_platform_interface
repository: https://github.com/Jjagg/drag_and_drop_flutter/tree/main/packages/drag_and_drop_flutter_platform_interface

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  collection: ^1.15.0
  cross_file: ^0.3.2
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^1.0.4
